file = open("readTextFile",'+w')
file.write("Hello World")
file = open("readTextFile",'+r')
data = file.readline()
print(data)
file.close()
file = open("readTextFile",'+a')
file.write("Welcome to Earth")
file = open("readTextFile",'+r')
data = file.readline()
print(data)
file.close()
#