[project]
name = "kitchenelite"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2.10",
    "dotenv>=0.9.9",
    "fastapi>=0.128.0",
    "langchain>=1.2.7",
    "langchain-community>=0.4.1",
    "langchain-groq>=1.1.1",
    "langchain-mistralai>=1.1.1",
    "mistralai>=1.10.1",
    "uvicorn>=0.40.0",
]
